Link.create!([
  {value: nil, source: 1, target: 55},
  {value: nil, source: 1, target: 20},
  {value: nil, source: 1, target: 21},
  {value: nil, source: 1, target: 22},
  {value: nil, source: 1, target: 26},
  {value: nil, source: 1, target: 23},
  {value: nil, source: 2, target: 41},
  {value: nil, source: 2, target: 42},
  {value: nil, source: 2, target: 23},
  {value: nil, source: 3, target: 41},
  {value: nil, source: 3, target: 38},
  {value: nil, source: 3, target: 23},
  {value: nil, source: 4, target: 44},
  {value: nil, source: 4, target: 53},
  {value: nil, source: 4, target: 45},
  {value: nil, source: 4, target: 46},
  {value: nil, source: 5, target: 55},
  {value: nil, source: 5, target: 24},
  {value: nil, source: 5, target: 73},
  {value: nil, source: 5, target: 34},
  {value: nil, source: 5, target: 97},
  {value: nil, source: 5, target: 35},
  {value: nil, source: 5, target: 38},
  {value: nil, source: 5, target: 26},
  {value: nil, source: 5, target: 40},
  {value: nil, source: 6, target: 23},
  {value: nil, source: 7, target: 75},
  {value: nil, source: 7, target: 100},
  {value: nil, source: 7, target: 38},
  {value: nil, source: 7, target: 94},
  {value: nil, source: 7, target: 95},
  {value: nil, source: 7, target: 23},
  {value: nil, source: 8, target: 75},
  {value: nil, source: 8, target: 100},
  {value: nil, source: 8, target: 95},
  {value: nil, source: 8, target: 94},
  {value: nil, source: 8, target: 96},
  {value: nil, source: 8, target: 38},
  {value: nil, source: 8, target: 38},
  {value: nil, source: 8, target: 23},
  {value: nil, source: 9, target: 74},
  {value: nil, source: 9, target: 38},
  {value: nil, source: 10, target: 74},
  {value: nil, source: 9, target: 56},
  {value: nil, source: 9, target: 59},
  {value: nil, source: 10, target: 59},
  {value: nil, source: 11, target: 75},
  {value: nil, source: 11, target: 77},
  {value: nil, source: 11, target: 83},
  {value: nil, source: 12, target: 75},
  {value: nil, source: 12, target: 77},
  {value: nil, source: 12, target: 83},
  {value: nil, source: 13, target: 75},
  {value: nil, source: 13, target: 77},
  {value: nil, source: 13, target: 82},
  {value: nil, source: 13, target: 83},
  {value: nil, source: 14, target: 55},
  {value: nil, source: 14, target: 24},
  {value: nil, source: 14, target: 25},
  {value: nil, source: 14, target: 26},
  {value: nil, source: 14, target: 27},
  {value: nil, source: 14, target: 28},
  {value: nil, source: 14, target: 29},
  {value: nil, source: 14, target: 23},
  {value: nil, source: 15, target: 52},
  {value: nil, source: 16, target: 64},
  {value: nil, source: 16, target: 86},
  {value: nil, source: 16, target: 87},
  {value: nil, source: 16, target: 88},
  {value: nil, source: 16, target: 87},
  {value: nil, source: 16, target: 88},
  {value: nil, source: 16, target: 61},
  {value: nil, source: 16, target: 38},
  {value: nil, source: 16, target: 63},
  {value: nil, source: 17, target: 65},
  {value: nil, source: 17, target: 66},
  {value: nil, source: 17, target: 67},
  {value: nil, source: 18, target: 64},
  {value: nil, source: 18, target: 68},
  {value: nil, source: 18, target: 70},
  {value: nil, source: 18, target: 71},
  {value: nil, source: 19, target: 63},
  {value: nil, source: 7, target: 89},
  {value: nil, source: 38, target: 39},
  {value: nil, source: 38, target: 43},
  {value: nil, source: 38, target: 57},
  {value: nil, source: 46, target: 47},
  {value: nil, source: 46, target: 48},
  {value: nil, source: 46, target: 50},
  {value: nil, source: 46, target: 51},
  {value: nil, source: 46, target: 52},
  {value: nil, source: 10, target: 58}
])
Node.create!([
  {name: "Home", color: "#ff05a3", node_type: 1, enumerate: "0.0"},
  {name: "Work Landing", color: "#5005ff", node_type: 1, enumerate: "1.0"},
  {name: "Work Taxonomy", color: "#115ad0", node_type: 1, enumerate: "1.1"},
  {name: "Work Detail", color: "#075ebb", node_type: 1, enumerate: "1.0.1"},
  {name: "Expertise", color: "#ffc107", node_type: 1, enumerate: "2.0"},
  {name: "Capability Detail", color: "#ffc107", node_type: 1, enumerate: "2.1"},
  {name: "Industry Detail", color: "#ffc107", node_type: 1, enumerate: "2.2"},
  {name: "Solution Detail", color: "#ffc107", node_type: 1, enumerate: "2.3"},
  {name: "Insights", color: "#ffc107", node_type: 1, enumerate: "3.0"},
  {name: "Archive Template", color: "#ffc107", node_type: 1, enumerate: "3.1"},
  {name: "Article Detail", color: "#ffc107", node_type: 1, enumerate: "3.0.1"},
  {name: "News Detail", color: "#ffc107", node_type: 1, enumerate: "3.0.2"},
  {name: "Podcast Detail", color: "#ffc107", node_type: 1, enumerate: "3.0.3"},
  {name: "About", color: "#ffc107", node_type: 1, enumerate: "4.0"},
  {name: "Truth & Beauty", color: "#ffc107", node_type: 1, enumerate: "4.1"},
  {name: "Careers", color: "#ffc107", node_type: 1, enumerate: "5.0"},
  {name: "Current Openings", color: "#ffc107", node_type: 1, enumerate: "5.1"},
  {name: "Job Detail", color: "#ffc107", node_type: 1, enumerate: "5.1.1"},
  {name: "Contact", color: "#ffc107", node_type: 1, enumerate: "6.0"},
  {name: "Featured Hero Video", color: "#ffc107", node_type: 2, enumerate: "01"},
  {name: "Featured Posts Promo", color: "#ffc107", node_type: 2, enumerate: "02"},
  {name: "Animated Logo Garden", color: "#ffc107", node_type: 2, enumerate: "03"},
  {name: "CTA Blade 1", color: "#ffc107", node_type: 2, enumerate: "04"},
  {name: "Hero Video", color: "#ffc107", node_type: 2, enumerate: "05"},
  {name: "3-Column Text Promo", color: "#ffc107", node_type: 2, enumerate: "06"},
  {name: "Blockquote", color: "#ffc107", node_type: 2, enumerate: "07"},
  {name: "Scrolling Timeline", color: "#ffc107", node_type: 2, enumerate: "08"},
  {name: "CTA Blade 2", color: "#ffc107", node_type: 2, enumerate: "09"},
  {name: "Department Grid", color: "#ffc107", node_type: 2, enumerate: "10"},
  {name: "Leadership Grid", color: "#ffc107", node_type: 2, enumerate: "11"},
  {name: "Audio List", color: "#ffc107", node_type: 2, enumerate: "12"},
  {name: "Link List", color: "#ffc107", node_type: 2, enumerate: "13"},
  {name: "Image Card Deck", color: "#ffc107", node_type: 2, enumerate: "14"},
  {name: "Sliding Card Deck", color: "#ffc107", node_type: 2, enumerate: "15"},
  {name: "Partner Card", color: "#ffc107", node_type: 2, enumerate: "16"},
  {name: "Scrolling Marquee", color: "#ffc107", node_type: 2, enumerate: "17"},
  {name: "Taxonomy Toggle", color: "#ffc107", node_type: 2, enumerate: "18"},
  {name: "Flexible Post Grid", color: "#ffc107", node_type: 2, enumerate: "19"},
  {name: "Work Card", color: "#ffc107", node_type: 2, enumerate: "20"},
  {name: "Themeable Hero", color: "#ffc107", node_type: 2, enumerate: "21"},
  {name: "List Group", color: "#ffc107", node_type: 2, enumerate: "22"},
  {name: "Themeable Content Block", color: "#ffc107", node_type: 2, enumerate: "23"},
  {name: "2-up Stats List", color: "#ffc107", node_type: 2, enumerate: "24"},
  {name: "List with Label", color: "#ffc107", node_type: 2, enumerate: "25"},
  {name: "1-Up Image", color: "#ffc107", node_type: 2, enumerate: "26"},
  {name: "Full Width Carousel", color: "#ffc107", node_type: 2, enumerate: "27"},
  {name: "2-Up Image", color: "#ffc107", node_type: 2, enumerate: "28"},
  {name: "Image with Caption", color: "#ffc107", node_type: 2, enumerate: "29"},
  {name: "Text Block with Label", color: "#ffc107", node_type: 2, enumerate: "30"},
  {name: "Simple Button CTA", color: "#ffc107", node_type: 2, enumerate: "31"},
  {name: "Page Heading", color: "#ffc107", node_type: 2, enumerate: "32"},
  {name: "Featured Post", color: "#ffc107", node_type: 2, enumerate: "33"},
  {name: "Post Card", color: "#ffc107", node_type: 2, enumerate: "34"},
  {name: "Filter Buttons", color: "#ffc107", node_type: 2, enumerate: "35"},
  {name: "Post Card Grid", color: "#ffc107", node_type: 2, enumerate: "36"},
  {name: "TBD", color: "#ffc107", node_type: 2, enumerate: "37"},
  {name: "Mini Job Listing", color: "#ffc107", node_type: 2, enumerate: "38"},
  {name: "Side Scrolling Gallery", color: "#ffc107", node_type: 2, enumerate: "39"},
  {name: "Office Listing", color: "#ffc107", node_type: 2, enumerate: "40"},
  {name: "Image Hero", color: "#ffc107", node_type: 2, enumerate: "41"},
  {name: "Team / Office Filter", color: "#ffc107", node_type: 2, enumerate: "42"},
  {name: "Department Listing", color: "#ffc107", node_type: 2, enumerate: "43"},
  {name: "Job Listing", color: "#ffc107", node_type: 2, enumerate: "44"},
  {name: "Sticky Job Detail Sidebar", color: "#ffc107", node_type: 2, enumerate: "45"},
  {name: "Job Introduction", color: "#ffc107", node_type: 2, enumerate: "46"},
  {name: "Job Features", color: "#ffc107", node_type: 2, enumerate: "47"},
  {name: "Job Description", color: "#ffc107", node_type: 2, enumerate: "48"},
  {name: "Job Application", color: "#ffc107", node_type: 2, enumerate: "49"},
  {name: "Interactive Diagram", color: "#ffc107", node_type: 2, enumerate: "50"},
  {name: "Insights Heading", color: "#ffc107", node_type: 2, enumerate: "51"},
  {name: "Post Banner", color: "#ffc107", node_type: 2, enumerate: "52"},
  {name: "Post Meta", color: "#ffc107", node_type: 2, enumerate: "53"},
  {name: "Post Sharing", color: "#ffc107", node_type: 2, enumerate: "54"},
  {name: "Post Intro", color: "#ffc107", node_type: 2, enumerate: "55"},
  {name: "Post Content Block", color: "#ffc107", node_type: 2, enumerate: "56"},
  {name: "Post Media Block", color: "#ffc107", node_type: 2, enumerate: "57"},
  {name: "Post Pardot Form", color: "#ffc107", node_type: 2, enumerate: "58"},
  {name: "Podcast Widget", color: "#ffc107", node_type: 2, enumerate: "59"},
  {name: "Related Posts", color: "#ffc107", node_type: 2, enumerate: "60"},
  {name: "Video Hero with Text Overlay", color: "#ffc107", node_type: 2, enumerate: "61"},
  {name: "Careers Intro", color: "#ffc107", node_type: 2, enumerate: "62"},
  {name: "CTA Blade 3", color: "#ffc107", node_type: 2, enumerate: "63"},
  {name: "Mini Card Slider", color: "#ffc107", node_type: 2, enumerate: "64"},
  {name: "Centered Call Out Card", color: "#ffc107", node_type: 2, enumerate: "65"},
  {name: "Jump Links", color: "#ffc107", node_type: 2, enumerate: "66"},
  {name: "Open Positions List", color: "#ffc107", node_type: 2, enumerate: "38"},
  {name: "Side Scrolling Gallery", color: "#ffc107", node_type: 2, enumerate: "39"},
  {name: "Office Listing", color: "#ffc107", node_type: 2, enumerate: "40"},
  {name: "Body Block w/ Eyebrow", color: "#ffc107", node_type: 2, enumerate: "67"},
  {name: "Specialists", color: "#ffc107", node_type: 2, enumerate: "68"},
  {name: "Stats and Quotes", color: "#ffc107", node_type: 2, enumerate: "69"},
  {name: "Capabilities Overview", color: "#ffc107", node_type: 2, enumerate: "70"},
  {name: "Promo Grid", color: "#ffc107", node_type: 2, enumerate: "71"},
  {name: "Contact Heading", color: "#ffc107", node_type: 2, enumerate: "72"},
  {name: "Contact Module", color: "#ffc107", node_type: 2, enumerate: "73"},
  {name: "Logo Garden 2", color: "#ffc107", node_type: 2, enumerate: "74"},
  {name: "Department Item", color: "#ffc107", node_type: 2, enumerate: "10.1"},
  {name: "Audio Item", color: "#ffc107", node_type: 2, enumerate: "12.1"},
  {name: "Image Card", color: "#ffc107", node_type: 2, enumerate: "14.1"},
  {name: "Image Card Button List", color: "#ffc107", node_type: 2, enumerate: "14.2"}
])
